### ISSUE TITLE
Error: define cannot be used indirect

### ISSUE THREAD

**Issue by ghost** [channikhabra/yarr#21]
`git checkout 7-offline-storage-with-dexiejs &&
npm start`

On browser console, i got the error as,

``` javascript
Error: define cannot be used indirect
 module.exports = function() { throw new Error("define cannot be used indirect");...
```

I am seeing this issue is discussed at https://github.com/webpack/webpack/issues/138 but not sure, how to fix this in yarr repo?

**Comment by bitspook** [comment]
Hey Madhavan,

In the chapter 7 when we get to using dexie, I've mentioned a hack to get over this hurdle. Check here:

https://github.com/channikhabra/yarr/tree/7-offline-storage-with-dexiejs#webpack-dexie-fixhack
