### ISSUE TITLE
Stuck at chapter 5, no "styles.css" will be created whatsoever, but no obvious errors too

### ISSUE THREAD

**Issue by spex66** [channikhabra/yarr#22]
Amazing tutorial... I'm really addicted and hooked!
Thanks for all the effort, it is so valuable to see the step-by-step transformation along with your documentation!

First time using webpack, but a really nice experience too having this hot updates working on every change :)

Maybe it is because it is Oct '15 and the versions of webpack or other npm modules have changed... but I cannot can get the "styles.css" created.

But no errors, just no `http://localhost:8080/styles.css` appears.
I assume to see them under yarr/dist beside the app.js, correct?

On top of the "npm start" log, I can spot "styles.css" with 24.3kb:

```
                               Asset      Size  Chunks             Chunk Names
                              app.js   2.73 MB       0  [emitted]  main
0.77455e93b649320897a5.hot-update.js   2.03 kB       0  [emitted]  main
77455e93b649320897a5.hot-update.json  36 bytes          [emitted]
                          styles.css   24.3 kB       0  [emitted]  main
chunk    {0} app.js, 0.77455e93b649320897a5.hot-update.js, styles.css (main) 978 kB [rendered]
```

But not on my disk... and cannot be loaded from index.html.

I've tested this with `git checkout 5-fetch-feeds-and-styles` on your original codebase too, without my changes going through your tutorial... same effect.

Anything obvious which I've missed?
A typical noob error maybe?
I've spend too much time now, without _any_ progress to fix this... reading through tickets of other SASS or ExtractTextPlugin. 
So I was desperate enough to write an issue.

thx
Peter
(=PA=)

**Comment by bitspook** [comment]
Hey Peter,

What you're seeing is not really an error. Webpack work in mysterious ways (well, not really, but it sounds good to say). When we run a webpack-dev-server, it don't create any files on the disk at all. It keep them in the memory so that in can notify faster on file change (disk is always slow than RAM). I think you're trying with `npm start` or `webpack-dev-server` and noticing this thing. Have you tried `npm run build` yet? It shall create the files on disk (in `dist` folder) for distribution. 

From a webpack docs:

> webpack-dev-server: Serves all webpack assets from memory. Best performance.

https://webpack.github.io/docs/build-performance.html

> So I was desperate enough to write an issue.

No worries : ) Glad you liked the tutorial.

**Comment by spex66** [comment]
Hi Charanjit,
Your reply is very appreciated!
I've figured this "in RAM" feature out, too... very smart and extremely
helpful.

But then you would expect the the "styles.css" is served from RAM. But the
Ghostium styles are missing 100% in rendering. The weback dev-server is
smart enough to load it from RAM based on the <style...> tag you used in
the index.html?

Only thing you see in Chrome is the 404 , when it tried to access
http://localhost:8080/styles.css
Without any CSS the example looks pretty ugly :)

Any easy debug mode, to check the webpack processing/serving of the style,
you would recommend?

Writing from my mobile... hopefully all references are correct and the
typos don't hide the semantics :)
Peter
(=PA=)

**Comment by bitspook** [comment]
Hey Peter,

Sorry for the misunderstanding. I could replicate this. For some reason it has been working till now with no new changes. 

So this can be resolved by making this small change in `index.html`:

replace: `<link href="styles.css" rel="stylesheet"/>`

with: `<link href="dist/styles.css" rel="stylesheet"/>`

webpack would pick resources from `output.publicPath` in webpack config, which has been set to `/dist/`. I wonder why this was working so far. I guess this happened when I merged a pull request for better webpack config, but I remember testing it back then it was working fine. 

Anyway, sorry for your trouble.

**Comment by spex66** [comment]
Hi,
At least perfect, that you are able to reproduce it!
And that you have taken the time to do it :)
I don't mind the trouble, if there is a solution for it.

I'll check the change (which sounds reasonable for me) today.
But for production it needs to be changed to styles.css without the
"dist/..." I assume?
Will test it.
Regards
Peter
(=PA=)

**Comment by bitspook** [comment]
Yea webpack config for production needed to be changed. I think it's better if we keep the styles.css in dist itself for both cases. 

I have updated the git tags (chapters) and revised the git history to accommodate both changes, so you can do a force fetch (or a fresh clone) of this repo and check if you're still facing the issue.
