### ISSUE TITLE
Thanks for the awesome ride!

### ISSUE THREAD

**Issue by HighOnDrive** [channikhabra/yarr#3]
Absolutely brilliant, reading this has made so many of my intuitions about the state of present day frameworks much more resolved and concrete. Have you seen Cycle.js.org? This tutorial should map over without much change.

**Comment by bitspook** [comment]
Glad you liked it. Yea I've seen Cycle.js and I like it. It's awesome. I decided to write this tutorial "framework less" for several reasons; one was that I was getting sick of people obsessed about frameworks. I have nothing against frameworks, I use the most opinionated ones when it make sense. But I was getting fed up with people talking about how X framework make it easy to do Y, how fast it is bla bla, without giving a damn about what ideas it bring. This is more dangerous than it might sound, I've seen people creating galactic unmaintainable mess full of dangling state using frameworks which aim to avoid exactly that, namely React (one of the perks of being a freelancer is that you get to work through a lot of mess for some quick bucks).

I just wanted to see for myself what can be accomplished with the right combination of technologies and ideas. So I took React's isolated stateless components and virtual-dom, and Meteor's reactivity as ideals and thought to try building an app without having a framework to force my hand a certain way. The components in this app aren't 100% stateless, but they can be made with little more thought. All it's resemblance to cycle.js is coincidence, which I think adds to the natural flow of writing apps cycle.js brings, making it even more awesome (I haven't ever used cycle.js though, but Andre Staltz said it's similar to cycle so I believe him 😛). 

Perhaps I should make a v2 later some time, and we'll make transition to cycle.js by inventing it on our way there.
